import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/shared/Header";
import ReduxProvider from "@/store/provider";
import Footer from "@/components/shared/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbar = [
    {
      name: "Product",
      link: "localhost:3000/",
    },
    {
      name: "Banner",
      link: "localhost:/3000/",
    },
    {
      name: "About",
      link: "localhost:/3000/",
    },
    {
      name: "Contact",
      link: "localhost:/3000/",
    },
  ];
  return (
    <div>
      <Header navbar={navbar} />
      <main className="py-14">{children}</main>
      <Footer />
    </div>
  );
}
